### PR TITLE
Add support for Panjabi/Punjabi language, ISO code - pa

### PR DESCRIPTION
**Pull request by punjab**
Added support for Panjabi - 10th most widely spoken language in the world. ISO code for Gurmukhi Script of Panjabi (also called Punjabi) is pa. The test specs and completeness rake task against en.yml are both passing.

### CODE REVIEW

**Comment by punjab** [comment]
There seems to be incorrect Gemfile.lock checked in. Running `bundle install` installs `rails-i18n (4.0.7)` however, the current `Gemfile.lock` has `rails-i18n (4.0.6)`. 

Travis is failing giving following error.

`Could not find rails-i18n-4.0.6 in any of the sources`

**Comment by Gurpartap** [comment]
:+1:

**Comment by punjab** [comment]
Updating `rails-i18n (4.0.7)` now has Travis build passing.

**Comment by Gurpartap** [comment]
@punjab Please see my comments and suggestions on the commit diff at https://github.com/svenfuchs/rails-i18n/commit/a7d33d1b319bdbaa1da64ced0aa0d280891a3a09

:sweat_smile:

**Comment by punjab** [comment]
@Gurpartap Thanks for reviewing. I have submitted a pull request with your suggestion https://github.com/svenfuchs/rails-i18n/pull/601 . Also please see comments on a7d33d1

**Pull request merged**
