### PR TITLE
Added missing translations

### PR DESCRIPTION
**Pull request by jonas-jasas**

### CODE REVIEW

**Review by sunny — COMMENTED** [review]
Thanks! Can you add an entry to the CHANGELOG as well? 🙏🏻

**Review by sunny — APPROVED** [review]
❤️

**Comment by pama** [comment]
@jonas-jasas I'm sorry but it is raising a merge error. Could you fix it so I can merge it? Thanks!

**Comment by jonas-jasas** [comment]
Conflicts solved

**Pull request merged**
