### PR TITLE
Add cy locale

### PR DESCRIPTION
**Pull request by hmzasif**
**Add Welsh(CY) locale**

**@AledBidder**, can you please review this PR to verify the Welsh locale values, especially the unit values for `EB` and `PB`? Thanks!

### CODE REVIEW

**Comment by pama** [comment]
Ralated to #1006

**Comment by AledBidder** [comment]
Thank you very much for doing this. I will make sure to review at some point this week 👍

**Comment by pama** [comment]
I'm considering merging this code as is? Any objection?

**Comment by AledBidder** [comment]
@pama, I'm sorry I haven't had time to conduct a proper review. I've recently had my first child and so time has been in short supply!

I have managed to look over everything though and whilst there were small things I would change I don't think there are any glaring mistakes. So I would be happy for this to be merged and then we can always follow up with an additional PR to make small changes if we want to 👍

**Comment by pama** [comment]
@AledBidder, congratulations on the arrival of your first child! No worries— contributions are always a gift and never an obligation.

**Comment by AledBidder** [comment]
Thank you @pama 🙌

**Comment by pama** [comment]
@hmzasif could you please fix the conflicts? Thanks!

**Comment by hmzasif** [comment]
@pama, I have removed the conflicts. Thank you!

**Pull request merged**
