### PR TITLE
en: Update and normalize locale file

### PR DESCRIPTION
**Pull request by jlduran**
Leave the `%{count}` changes to `1` for another PR (requires further discussion).

### CODE REVIEW

**Review by sunny — APPROVED** [review]
Good changes! Can you add an entry to the CHANGELOG?

**Comment by jlduran** [comment]
Thank you! CHANGELOG updated.
Let me know if there's something else missing.

**Review by sunny — APPROVED** [review]

**Comment by pama** [comment]
@jlduran could you fix the conflict?

**Comment by jlduran** [comment]
Done! Thank you!

**Review by sunny — APPROVED** [review]

**Comment by pama** [comment]
I'm not considering accepting this PR immediately because it introduces a new entry that won't be available before Rails 7.1.

I might fix or revert #1086 due to the same reason.

**Comment by jlduran** [comment]
> I'm not considering accepting this PR immediately because it introduces a new entry that won't be available before Rails 7.1.
> 
> I might fix or revert #1086 due to the same reason.

OK. That’s a valid reason. I have an idea. I’ll update this PR with it. Thank you!

**Comment by jlduran** [comment]
@pama Proposed #1091. I'll rebase this pull request if it gets accepted. Thank you for this pointing out.

**Comment by jlduran** [comment]
#1091 has been merged.
This pull request is a trivial cosmetic one now. I'll leave it here just in case, but it can be closed now.

Thank you!

**Comment by jlduran** [comment]
This can be closed now. Thank you!

**Pull request closed without merging**
