### PR TITLE
Add Sardinian (sc) translations

### PR DESCRIPTION
**Pull request by asereze**

### CODE REVIEW

**Comment by digitalfrost** [comment]
Could you please add the following two keys:
errors.messages.in and number.format.round_mode
https://github.com/rails/rails/blame/main/activemodel/lib/active_model/locale/en.yml#L35
and
https://github.com/rails/rails/blob/main/activesupport/lib/active_support/locale/en.yml#L48

**Comment by digitalfrost** [comment]
These keys will be added to the en.yml via this pull request:
https://github.com/svenfuchs/rails-i18n/pull/1042

**Comment by pama** [comment]
@digitalfrost shall we merge this one?

**Comment by asereze** [comment]
@digitalfrost Could you please give me some context about what those two strings mean? I need an example sentence for `errors.messages.in` and an explanation about what the default value in `number.format.round_mode` actually does. Since it looks like those strings are missing in all other locales I have no other examples to use for comparison. Anyway you could also merge this now and then I could just add those strings to the file later, when #1042 will be merged.

**Comment by pama** [comment]
@asereze you can find the Ruby on Rails default translations here: https://github.com/svenfuchs/rails-i18n/tree/master/rails/rails

**Comment by asereze** [comment]
@pama I didn't find a clear explanation there, the comment for `number.format.round_mode` is  [` # Determine how rounding is performed (see BigDecimal::mode)`](https://github.com/svenfuchs/rails-i18n/blob/master/rails/rails/active_support.yml#L47) but where can I find BigDecimal::mode? I need to know what the values are to be able to know if "default" is applicable to Sardinian. And [`errors.messages.in`](https://github.com/svenfuchs/rails-i18n/blob/master/rails/rails/active_model.yml#L35) doesn't have an example or explanation. Could you please tell me how "must be in %{count}" could be used?

**Comment by pama** [comment]
@asereze for `in` see https://guides.rubyonrails.org/active_record_validations.html#numericality and search for "must be in". 

for `round_mode`, it's used with helpers like [number_to_human](https://api.rubyonrails.org/classes/ActiveSupport/NumberHelper.html#method-i-number_to_human), and you can learn more about [BigDecima::mode](https://ruby-doc.org/stdlib-3.1.2/libdoc/bigdecimal/rdoc/BigDecimal.html#method-c-mode ) in the stdlib documentation. I don't see a reason to use something else besides the default, but I will let that to you :)

**Comment by pama** [comment]
@asereze we are getting errors when running the tests, is this something you can fix? Thanks!

**Comment by digitalfrost** [comment]
It's failing on
```
locale file is expected to be a subset of "rails/locale/en.yml"
```
because it is expecting the two new keys ```errors.messages.in``` and ```number.format.round_mode``` to be in en.yml

They have now be added to en.yml via 99252524a7c8bf98e282dbd27bcf0a393a63f547 and 53b50953fe8f27b04b6cf4ea1310b571c9d49fd0

**Comment by digitalfrost** [comment]
This workflow https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch
should fix the problem

**Pull request merged**
