### PR TITLE
Changed Turkish currency unit symbol.

### PR DESCRIPTION
**Pull request by computeus**

### CODE REVIEW

**Comment by kuroda** [comment]
@computeus 

On my browser, this character is rendered like `☒`. So, I am hesitant to accept your pull request.

**Comment by computeus** [comment]
@kuroda 

According to http://www.unicode.org/versions/Unicode6.2.0/ the Turkish Lira Sign is addded to Unicode.

**Comment by kuroda** [comment]
@computeus 

According to http://stackoverflow.com/questions/14117547/browser-support-and-workarounds-for-turkish-lira-sign (a post in 2013), few fonts support Turkish Lira Sign and one answer says

> it has usually taken about ten years or more from the adoption of a character into Unicode to its general availability in fonts.

My opinion is that we should wait for a while.

**Comment by digitalfrost** [comment]
Can be closed?

**Pull request closed without merging**
