### PR TITLE
South slavic pluralizers

### PR DESCRIPTION
**Pull request by toncid**
Outlined in #986.

### CODE REVIEW

**Review by movermeyer — APPROVED** [review]
Yup. I literally [wrote the same PR](https://github.com/svenfuchs/rails-i18n/compare/master...movermeyer:movermeyer/south_slavic_pluralization?expand=1) just now. 👍

**Comment by movermeyer** [comment]
Fixes #992

**Comment by movermeyer** [comment]
You should also update the comment at the [top of `east_slavic.rb`](https://github.com/svenfuchs/rails-i18n/blob/3656f278cd317cffffbf08dbacb4d0d7e9b70b19/lib/rails_i18n/common_pluralizations/east_slavic.rb#L4) to remove these languages

**Comment by toncid** [comment]
@movermeyer Thanks! I have made the amendments and updated tests to match the Unicode spec.

The PR tests now pass (apart from the unrelated `cy.yml` error).

**Pull request merged**
