### PR TITLE
Adding es-NI (Spanish Nicaragua) to rails-i18n (Whole translation for this region)

### PR DESCRIPTION
**Pull request by mldoscar**
Created an es-NI.yml es.NI.rb locales, contributing with my country
[rails-i18n.zip](https://github.com/svenfuchs/rails-i18n/files/172759/rails-i18n.zip)

**rails-i18n/rails/locale/es-NI.yml**
[https://gist.github.com/mldoscar/2aa6010a8031f7c4d7a9](https://gist.github.com/mldoscar/2aa6010a8031f7c4d7a9)

**rails-i18n/rails/pluralization/es-NI.rb**
[https://gist.github.com/mldoscar/b8084878cd5d04a06901](https://gist.github.com/mldoscar/b8084878cd5d04a06901)

Regards, colegues!

### CODE REVIEW

**Comment by kuroda** [comment]
@mldoscar Thanks for your contribution!

Could you rebase your commits and push again?

**Comment by mldoscar** [comment]
@kuroda i´m on it right now!

Regards

**Comment by mldoscar** [comment]
Check it out again:

**rails-i18n/rails/locale/es-NI.yml**
[https://gist.github.com/mldoscar/b8084878cd5d04a06901](https://gist.github.com/mldoscar/b8084878cd5d04a06901)

**rails-i18n/rails/pluralization/es-NI.rb**
[https://gist.github.com/mldoscar/b8084878cd5d04a06901](https://gist.github.com/mldoscar/b8084878cd5d04a06901)

**Comment by ghiculescu** [comment]
@mldoscar did this ever get merged?

**Pull request closed without merging**
